### ISSUE TITLE
GREAT APP NO ISSUES!!!!

### ISSUE THREAD

**Issue by wellkunnected** [omaralbeik/FoodTracker#3]
There isn't a way to simply comment on nice projects so I just wanted to let you know I was able to get this app to build and running it on my iphone 6+. I have some cool ideas I'd like to implement if thats ok with you, but awesome job! :)

**Comment by omaralbeik** [comment]
Feel free, it's an open source project, just change the API key. good luck with your project..

**Comment by wellkunnected** [comment]
Awesome! I'm checking out your other projects as well. You rock Omar 👍

**Comment by omaralbeik** [comment]
Glad to hear that, thanks 👍

**Comment by wellkunnected** [comment]
Certainly! Quick question, where can I obtain a new API key?

**Comment by omaralbeik** [comment]
https://ndb.nal.usda.gov/ndb/doc/index -> sign up

**Comment by omaralbeik** [comment]
And check out this API http://www.nutritionix.com/business/api
It might be helpful also

**Comment by wellkunnected** [comment]
Awesome will do! Thanks again Omar

On Mon, Feb 29, 2016 at 6:59 PM, Omar Albeik notifications@github.com
wrote:

> And check out this API http://www.nutritionix.com/business/api
> It might be helpful also
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/omaralbeik/NutritionCal/issues/3#issuecomment-190455708
> .

## 

Founded Well Kunnected, Inc 2010

**Comment by wellkunnected** [comment]
Also, I tried running the "spinny" app and keep getting an error where the
AVAudio player is set to "nil". Any tips on how to fix this so it runs?

On Mon, Feb 29, 2016 at 8:33 PM, Armani Rouse armanirouse@gmail.com wrote:

> Awesome will do! Thanks again Omar
> 
> On Mon, Feb 29, 2016 at 6:59 PM, Omar Albeik notifications@github.com
> wrote:
> 
> > And check out this API http://www.nutritionix.com/business/api
> > It might be helpful also
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/omaralbeik/NutritionCal/issues/3#issuecomment-190455708
> > .
> 
> ## 
> 
> Founded Well Kunnected, Inc 2010

## 

Founded Well Kunnected, Inc 2010
